version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  webserver:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "${LOCALHOST_PORT}:${WEBSERVER_PORT}"
    networks:
      - laravel
    volumes:
      - ./:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .docker/data/db:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:8.10.2
    restart: unless-stopped
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
      - "${ELASTICSEARCH_NODE_PORT}:${ELASTICSEARCH_NODE_PORT}"
    networks:
      - laravel
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/data/elasticsearch:/usr/share/elasticsearch/data
    depends_on:
      - db